from datetime import datetime
from sqlalchemy import (
    Column, String, Integer, Boolean, DateTime, Text, ForeignKey, Float
)
from sqlalchemy.orm import relationship
from backend.database import Base


class Case(Base):
    __tablename__ = "cases"

    id = Column(String, primary_key=True)
    # id is a UUID string, generated by the router

    case_name = Column(String(255), nullable=False)
    case_number = Column(String(100), unique=True, nullable=True)
    status = Column(String(50), default="Open")
    # status values: Open, Active, Closed, Archived

    priority = Column(String(50), default="Medium")
    # priority values: Low, Medium, High, Critical

    description = Column(Text, nullable=True)
    created_by = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    tags = Column(Text, default="[]")
    # tags stored as JSON string

    # Relationships
    evidence = relationship("Evidence", back_populates="case", cascade="all, delete-orphan")
    queries = relationship("QueryLog", back_populates="case", cascade="all, delete-orphan")
    entities = relationship("Entity", back_populates="case", cascade="all, delete-orphan")
    notes = relationship("Note", back_populates="case", cascade="all, delete-orphan")
    audit_logs = relationship("AuditLog", back_populates="case", cascade="all, delete-orphan")
    reports = relationship("Report", back_populates="case", cascade="all, delete-orphan")
    watchlist_keywords = relationship("WatchlistKeyword", back_populates="case", cascade="all, delete-orphan")


class Evidence(Base):
    __tablename__ = "evidence"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=False)
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)
    file_size_bytes = Column(Integer, default=0)
    file_path = Column(String(500), nullable=False)
    # path on disk relative to CASES_DIR

    sha256_hash = Column(String(64), nullable=True)
    ingested_at = Column(DateTime, default=datetime.utcnow)
    ingested_by = Column(String(255), nullable=False)
    status = Column(String(50), default="Uploaded")
    # status values: Uploaded, Queued,
    #   Processing, Indexed, Failed,
    #   Archived

    ingestion_job_id = Column(
        String, nullable=True)
    # Links to IngestionJob.id

    chunk_count = Column(Integer, default=0)
    entity_count = Column(Integer, default=0)
    notes = Column(Text, nullable=True)
    error_message = Column(Text, nullable=True)
    # stores error if status is Failed

    case = relationship("Case", back_populates="evidence")
    artifacts = relationship(
        "ForensicArtifact",
        back_populates="evidence",
        cascade="all, delete-orphan"
    )


class ForensicArtifact(Base):
    __tablename__ = "forensic_artifacts"

    id = Column(String, primary_key=True)
    evidence_id = Column(
        String, ForeignKey("evidence.id"), nullable=False)
    case_id = Column(
        String, ForeignKey("cases.id"), nullable=False)

    # Path inside the disk image
    internal_path = Column(String(1000), nullable=False)
    # e.g. /Users/john/Documents/secret.pdf

    filename = Column(String(255), nullable=False)
    file_extension = Column(String(50), nullable=True)
    file_size_bytes = Column(Integer, default=0)
    sha256_hash = Column(String(64), nullable=True)

    # MACB Timestamps
    modified_at = Column(String(50), nullable=True)
    accessed_at = Column(String(50), nullable=True)
    created_at_ts = Column(String(50), nullable=True)
    born_at = Column(String(50), nullable=True)

    # Extraction result
    extracted_text = Column(Text, nullable=True)
    extraction_type = Column(String(50), nullable=True)
    # values: text, pdf, sqlite, html, exif, unsupported

    exif_data = Column(Text, default="{}")
    # JSON string of EXIF metadata

    is_flagged = Column(Boolean, default=False)
    is_anomaly = Column(
        Boolean, default=False)
    anomaly_reasons = Column(
        Text, default="[]")
    # JSON array of anomaly type strings
    # e.g. ["after_hours", "backdated",
    #        "mass_modification"]

    shannon_entropy = Column(
        Float, nullable=True)
    # 0.0 to 8.0
    # > 7.5 = likely encrypted/compressed
    # > 7.0 = possibly packed/obfuscated

    is_deleted = Column(
        Boolean, default=False)
    # True = file was deleted on disk
    # but recovered by pytsk3

    gps_latitude = Column(
        Float, nullable=True)
    # Decimal degrees from EXIF GPS
    # e.g. 37.3861 (north = positive)

    gps_longitude = Column(
        Float, nullable=True)
    # Decimal degrees from EXIF GPS
    # e.g. -122.0839 (west = negative)

    stored_file_path = Column(
        String(1000), nullable=True)
    # Absolute path to saved file on disk
    # None = file was not saved (too large
    # or binary-only)

    stored_file_size = Column(
        Integer, default=0)
    # Actual bytes saved to disk

    is_viewable = Column(
        Boolean, default=False)
    # True if the file can be rendered
    # in the browser viewer

    extracted_at = Column(DateTime, default=datetime.utcnow)

    evidence = relationship("Evidence", back_populates="artifacts")


class QueryLog(Base):
    __tablename__ = "query_logs"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=False)
    evidence_id = Column(String, nullable=True)
    # nullable: query may span all evidence in case

    asked_by = Column(String(255), nullable=False)
    asked_at = Column(DateTime, default=datetime.utcnow)
    question_text = Column(Text, nullable=False)
    raw_llm_response = Column(Text, nullable=True)
    processed_response = Column(Text, nullable=True)
    chunks_used = Column(Text, default="[]")
    # JSON array of chunk references

    graph_context = Column(Text, nullable=True)
    model_used = Column(String(100), default="llama3.2:3b")
    cited_sentence_count = Column(Integer, default=0)
    uncited_sentence_count = Column(Integer, default=0)
    response_time_ms = Column(Integer, default=0)
    is_flagged = Column(Boolean, default=False)
    # investigator can flag important queries

    case = relationship("Case", back_populates="queries")


class Entity(Base):
    __tablename__ = "entities"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=False)
    evidence_id = Column(String, nullable=True)
    name = Column(String(255), nullable=False)
    entity_type = Column(String(50), nullable=False)
    # values: Person, Location, Organization, IP, File

    frequency = Column(Integer, default=1)
    aliases = Column(Text, default="[]")
    # JSON array of alternative names found

    is_flagged = Column(Boolean, default=False)
    # investigator can flag key entities

    notes = Column(Text, nullable=True)
    first_seen_at = Column(DateTime, default=datetime.utcnow)

    case = relationship("Case", back_populates="entities")


class Note(Base):
    __tablename__ = "notes"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=False)
    linked_to_type = Column(String(50), nullable=True)
    # values: Case, Evidence, Entity, Query

    linked_to_id = Column(String, nullable=True)
    author = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    content = Column(Text, nullable=False)
    is_flagged = Column(Boolean, default=False)

    case = relationship("Case", back_populates="notes")


class AuditLog(Base):
    __tablename__ = "audit_logs"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=True)
    # nullable: some actions are not case-specific
    # e.g. app startup, new case creation

    action_type = Column(String(100), nullable=False)
    # values: CASE_CREATED, CASE_UPDATED,
    #   CASE_CLOSED, FILE_UPLOADED, FILE_INGESTED,
    #   QUERY_MADE, REPORT_GENERATED, NOTE_ADDED,
    #   ENTITY_FLAGGED, QUERY_FLAGGED

    performed_by = Column(String(255), nullable=False)
    performed_at = Column(DateTime, default=datetime.utcnow)
    details = Column(Text, default="{}")
    # JSON blob with action-specific details
    
    severity = Column(String(20), default="info")
    # info, warning, error, critical

    machine_id = Column(String(255), nullable=True)
    # hostname of machine that performed action

    case = relationship("Case", back_populates="audit_logs")


class Report(Base):
    __tablename__ = "reports"

    id = Column(String, primary_key=True)
    case_id = Column(String, ForeignKey("cases.id"), nullable=False)
    generated_at = Column(DateTime, default=datetime.utcnow)
    generated_by = Column(String(255), nullable=False)
    report_type = Column(String(100), nullable=False)
    # values: Case Summary, Query Transcript,
    #   Entity Report, Timeline, Full Investigation

    file_path = Column(String(500), nullable=True)
    sha256_hash = Column(String(64), nullable=True)
    query_ids_included = Column(Text, default="[]")
    # JSON array of QueryLog IDs in this report

    page_count = Column(Integer, default=0)
    status = Column(String(50), default="Generating")
    # values: Generating, Complete, Failed

    case = relationship("Case", back_populates="reports")


class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True)
    username = Column(
        String(100),
        unique=True,
        nullable=False,
        index=True
    )
    email = Column(
        String(255),
        unique=True,
        nullable=False,
        index=True
    )
    hashed_password = Column(
        String(255),
        nullable=False
    )
    full_name = Column(
        String(255),
        nullable=False
    )
    role = Column(
        String(50),
        default="Analyst",
        nullable=False
    )
    # Role values:
    # Admin       — full system access
    # Investigator— create/manage cases,
    #               upload, query
    # Analyst     — view + query, no upload
    # Viewer      — read-only

    is_active = Column(
        Boolean, default=True)
    created_at = Column(
        DateTime, default=datetime.utcnow)
    last_login = Column(
        DateTime, nullable=True)
    failed_login_attempts = Column(
        Integer, default=0)
    locked_until = Column(
        DateTime, nullable=True)
    # Account locked until this time.
    # None = not locked.

    totp_secret = Column(
        String(32), nullable=True)
    totp_enabled = Column(
        Boolean, default=False)
    
    preferences = relationship("UserPreference", back_populates="user", uselist=False, cascade="all, delete-orphan")


class UserPreference(Base):
    __tablename__ = "user_preferences"

    id = Column(String, primary_key=True)
    user_id = Column(
        String,
        ForeignKey("users.id"),
        nullable=False,
        unique=True
    )
    theme = Column(String(50), default="dark")
    timezone = Column(String(50), default="UTC")
    api_keys = Column(Text, default="{}") # JSON dictionary of service -> key
    # Show the CPU/RAM telemetry panel on the Evidence page. Some
    # investigators never look at hardware stats, so it can be switched
    # off in Settings > Preferences. Defaults to on for existing users.
    show_system_resources = Column(Boolean, default=True, nullable=False)

    user = relationship("User", back_populates="preferences")


class CaseAccess(Base):
    __tablename__ = "case_access"

    id = Column(String, primary_key=True)
    case_id = Column(
        String,
        ForeignKey("cases.id"),
        nullable=False
    )
    user_id = Column(
        String,
        ForeignKey("users.id"),
        nullable=False
    )
    granted_by = Column(
        String,
        nullable=False
    )
    granted_at = Column(
        DateTime,
        default=datetime.utcnow
    )
    role_on_case = Column(
        String(50),
        default="Investigator"
    )
    # Investigator or Analyst


class WatchlistKeyword(Base):
    __tablename__ = "watchlist_keywords"

    id = Column(String, primary_key=True)
    case_id = Column(
        String,
        ForeignKey("cases.id"),
        nullable=False
    )
    keyword = Column(
        String(255),
        nullable=False
    )
    category = Column(
        String(100),
        nullable=True
    )
    # e.g. "suspect_name", "location",
    # "financial_term", "malware_indicator"

    added_by = Column(
        String(255),
        nullable=False
    )
    added_at = Column(
        DateTime,
        default=datetime.utcnow
    )
    hit_count = Column(
        Integer, default=0
    )
    # Incremented each time a new
    # artifact matches this keyword

    is_active = Column(
        Boolean, default=True
    )

    case = relationship("Case", back_populates="watchlist_keywords")


class IngestionJob(Base):
    __tablename__ = "ingestion_jobs"

    id = Column(String, primary_key=True)
    evidence_id = Column(
        String,
        ForeignKey("evidence.id"),
        nullable=False,
        unique=True
    )
    case_id = Column(
        String,
        ForeignKey("cases.id"),
        nullable=False
    )
    status = Column(
        String(50),
        default="Queued"
    )
    # Queued, Running, Paused,
    # Completed, Failed, Cancelled

    queue_position = Column(
        Integer, default=0)
    # Order in which to process

    progress_percent = Column(
        Integer, default=0)
    current_step = Column(
        String(255), nullable=True)
    # e.g. "Step 2/5: Extracting text"

    estimated_seconds = Column(
        Integer, nullable=True)
    # Estimated total time in seconds

    elapsed_seconds = Column(
        Integer, default=0)

    # Resource budget
    min_free_ram_mb = Column(
        Integer, default=2048)
    # Pause if available RAM drops below
    # this value (default 2GB free)

    cpu_throttle_percent = Column(
        Integer, default=100)
    # 100 = full speed
    # 50 = sleep 1s between batches
    # 25 = sleep 3s between batches
    # Which accuracy/time profile to ingest under:
    # 'fastest' | 'normal' | 'accurate'.
    # See backend/modules/ingestion_modes.py. Rows written before this
    # column existed are NULL and resolve to 'normal' at runtime, so the
    # migration backfills rather than forcing a NOT NULL constraint.
    ingestion_mode = Column(
        String(20), nullable=True)

    # Timestamps
    queued_at = Column(
        DateTime, default=datetime.utcnow)
    started_at = Column(
        DateTime, nullable=True)
    completed_at = Column(
        DateTime, nullable=True)

    error_message = Column(
        Text, nullable=True)
    created_by = Column(
        String(255), nullable=False)


# ── Credential Scanner ──────────────────────────────────────────────────────

class CredentialFinding(Base):
    __tablename__ = "credential_findings"

    id = Column(String, primary_key=True)
    artifact_id = Column(
        String,
        ForeignKey("forensic_artifacts.id"),
        nullable=True)
    evidence_id = Column(
        String, nullable=False)
    case_id = Column(
        String,
        ForeignKey("cases.id"),
        nullable=False)

    credential_type = Column(
        String(100), nullable=False)
    # password, api_key, private_key,
    # credit_card, email, token,
    # connection_string, ssh_key

    matched_value = Column(
        Text, nullable=False)
    # Partially redacted value

    context = Column(Text, nullable=True)
    # Surrounding text (60 chars each side)

    source_file = Column(
        String(500), nullable=True)
    internal_path = Column(
        String(1000), nullable=True)

    is_confirmed = Column(
        Boolean, default=False)
    is_false_positive = Column(
        Boolean, default=False)

    found_at = Column(
        DateTime, default=datetime.utcnow)

    severity = Column(
        String(20), default="medium")
    # low, medium, high, critical
